---
- hosts: all
  vars:
    media_dir: '/data/library'
    admin_user: googley35

  pre_tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes
      become: true
    - name: Ensure user "{{ admin_user }}" exists
      user:
        name: '{{ admin_user }}'
        home: /var/lib/{{ admin_user }}
        uid: 1005

  roles:
    - role: mikegleasonjr.firewall
      firewall_v4_configure: true
      firewall_v6_configure: true
      firewall_v4_default_rules:
        001 default policies:
          - -P INPUT ACCEPT
          - -P OUTPUT ACCEPT
          - -P FORWARD DROP
        002 allow loopback:
          - -A INPUT -i lo -s 127.0.0.0/8 -d 127.0.0.0/8 -j ACCEPT
        003 allow ping replies:
          - -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
          - -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
        004 allow reverse proxy and home:
          - -A INPUT -s 198.245.51.132 -j ACCEPT
          - -A INPUT -s 82.229.61.52 -j ACCEPT
        100 allow established related:
          - -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
        200 allow ssh:
          - -A INPUT -p tcp --dport ssh -j ACCEPT
        201 allow apps:
          # Plex
          - -A INPUT -p tcp --dport 32400 -j ACCEPT
          # Transmission
          - -A INPUT -p tcp --dport 9091 -j ACCEPT
          # Sonarr
          - -A INPUT -p tcp --dport 8989 -j ACCEPT
        999 drop everything:
          - -P INPUT DROP
      firewall_v6_default_rules:
        999 drop everything:
          - -P INPUT DROP
          - -P OUTPUT DROP
          - -P FORWARD DROP
      become: true

    - role: marvinpinto.plex
      plex_server_version: '1.4.3.3433-03e4cfa35'
      plex_app_transcode_directory: '/data/transcode'
      plex_app_library_directory: '{{ media_dir }}'
      become: true

    - role: cmacrae.sonarr
      sonarr_user_name: '{{ admin_user }}'
      sonarr_group_name: '{{ admin_user }}'
      sonarr_user_uid: 1005
      sonarr_group_gid: 1005
      sonarr_user_home: /var/lib/{{ sonarr_user_name }}
      become: true

    - role: elboletaire.transmission
      transmission_user: '{{ admin_user }}'
      transmission_password: '{{ admin_password }}'
      transmission_url: '/transmission/'
      transmission_rpc_auth_enabled: true
      transmission_rpc_whitelist_enabled: false
      transmission_rpc_whitelist: 127.0.0.1
      transmission_rpc_auth_required: true
      transmission_umask: 2
      transmission_download_dir: '{{ media_dir }}'
      transmission_incomplete_dir_enabled: true
      transmission_incomplete_dir: '{{ media_dir }}/.incomplete'
      transmission_watch_dir_enabled: false
      transmission_watch_dir: '{{ media_dir }}/torrents'
      transmission_ratio_limit_enabled: false
      transmission_ratio_limit: 2
      transmission_speed_limit_up_enabled: true
      transmission_speed_limit_up: 2
      transmission_speed_limit_down_enabled: false
      transmission_speed_limit_down: 100
      transmission_blocklist_enabled: false
      transmission_blocklist_url: http://www.example.com/blocklist
      become: true
