---
- hosts: all
  vars:
    media_dir: '/data/library'
    admin_user: googley35
    h5ai_url: https://release.larsjung.de/h5ai/h5ai-0.29.0.zip

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Ensure git is installed
      apt:
        name: git
        state: present
      become: true
    - name: Ensure user '{{ admin_user }}' exists
      user:
        name: '{{ admin_user }}'
        home: /var/lib/{{ admin_user }}
        uid: 1005

  roles:
    - role: geerlingguy.firewall
      firewall_allowed_tcp_ports:
        - 32400
        - 51413
      firewall_allowed_udp_ports: []
      firewall_additional_rules:
        - 'iptables -I INPUT -p tcp -s {{ reverse_proxy_addr }}/32 -j ACCEPT'
        - 'iptables -I INPUT -p tcp -s 82.229.61.52 -j ACCEPT'
        - 'iptables -t filter -A OUTPUT -m owner --gid-owner debian-transmission -j ACCEPT'
      become: true

    - role: marvinpinto.plex
      plex_server_version: '1.4.4.3495-edef59192'
      plex_app_transcode_directory: '/data/transcode'
      plex_app_library_directory: '{{ media_dir }}'
      become: true

    - role: cmacrae.sickrage
      sickrage_user_name: '{{ admin_user }}'
      sickrage_group_name: '{{ admin_user }}'
      sickrage_user_uid: 1005
      sickrage_group_gid: 1005
      sickrage_user_home: /var/lib/{{ sickrage_user_name }}
      sickrage_port: 8081
      become: true

    - role: marvinpinto.couchpotato
      couchpotato_app_data_directory: '{{ media_dir }}'
      couchpotato_daemon_user: '{{ admin_user }}'

    - role: elboletaire.transmission
      transmission_user: '{{ admin_user }}'
      transmission_password: '{{ admin_password }}'
      transmission_url: '/transmission/'
      transmission_rpc_auth_enabled: true
      transmission_rpc_whitelist_enabled: false
      transmission_rpc_whitelist: 127.0.0.1
      transmission_rpc_auth_required: false
      transmission_umask: 2
      transmission_download_dir: '{{ media_dir }}'
      transmission_incomplete_dir_enabled: true
      transmission_incomplete_dir: '{{ media_dir }}/.incomplete'
      transmission_watch_dir_enabled: false
      transmission_watch_dir: '{{ media_dir }}/torrents'
      transmission_ratio_limit_enabled: false
      transmission_ratio_limit: 2
      transmission_speed_limit_up_enabled: true
      transmission_speed_limit_up: 1000
      transmission_speed_limit_down_enabled: false
      transmission_speed_limit_down: 100
      transmission_blocklist_enabled: false
      transmission_blocklist_url: http://www.example.com/blocklist
      become: true

    - role: geerlingguy.nginx
      nginx_user: '{{ admin_user }}'
      nginx_vhosts:
        - listen: '8080 default_server'
          server_name: '_'
          root: '/data'
          index: '/library/_h5ai/public/index.php'
          extra_parameters: |
            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }

            location / {
                allow {{ reverse_proxy_addr }};
                allow 127.0.0.1;
                deny all;
            }
      nginx_remove_default_vhost: true
      become: true

    - role: geerlingguy.php
      php_packages_state: 'latest'
      php_install_recommends: yes
      php_executable: 'php'
      php_enable_php_fpm: true
      php_fpm_listen: '127.0.0.1:9000'
      php_fpm_pool_user: '{{ admin_user }}'
      php_webserver_daemon: 'nginx'
      php_packages:
        - php-fpm
        - php-gd
      become: true


  tasks:
    - name: Stop SickRage
      become: true
      service:
        name: sickrage
        state: stopped
   
    - name: Ensure sickrage web_root is /sickrage
      become: true
      lineinfile:
        dest: '/var/lib/{{ admin_user }}/.sickrage/config.ini'
        regexp: '^web_root ='
        line: 'web_root = "/sickrage"'
      register: sickrage_config
   
    - name: Start SickRage
      become: true
      service:
        name: sickrage
        state: started
    - name: Ensure h5ai requirements are installed
      apt:
        name: '{{ item }}'
      with_items:
        - imagemagick
        - ffmpeg
        - tar
        - zip
    - name: Install h5ai
      unarchive:
        src: '{{ h5ai_url }}'
        dest: '{{ media_dir }}'
        remote_src: yes
    - name: Configure h5ai
      template:
        src: templates/h5ai/options.json.j2
        dest: '{{ media_dir }}/_h5ai/private/conf/options.json'
        owner: root
        group: root
        mode: 0644
